### ISSUE TITLE
Regular Expression Not Imported

### ISSUE THREAD

**Issue by NickVig** [datamountaineer/python-serializers#6]
Hi,

Apologies if I have not addressed this correctly; it is my first attempt at listing an error on github.

Upon calling client.list_all() I get the error below. I assume this is because the regular expression package is not imported?

Thanks,
Nick

C:\Program Files\Anaconda3\lib\site-packages\datamountaineer\schemaregistry\client\SchemaRegistryClient.py in list_all(self)
    173 
    174         for subject in result:
--> 175             m = re.match("(.*)-(value|key)$", subject)
    176             if m:
    177                 if m.groups()[1] == 'key':

NameError: name 're' is not defined

**Comment by andrewstevenson** [comment]
@NickVig We aren't actively support this anymore. It was developed before the Python client from Confluent had Schema Registry support. I would recommend using it, otherwise PRs are welcome!
